// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMbDCgXNK49FAgTQaR2qjDVrpaGjUK38',
    appId: '1:985128793202:web:7257c3a2e3a2b77d5dfeeb',
    messagingSenderId: '985128793202',
    projectId: 'myfin-194ee',
    authDomain: 'myfin-194ee.firebaseapp.com',
    storageBucket: 'myfin-194ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5peQ8PEgwY4w4r8Drsc7Z-euaJP75hVE',
    appId: '1:985128793202:android:9ce2a22c56a145815dfeeb',
    messagingSenderId: '985128793202',
    projectId: 'myfin-194ee',
    storageBucket: 'myfin-194ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbdYOsYQvzPHek_42xEWdgWqY1HR0Ur_U',
    appId: '1:985128793202:ios:76cfe123e1ccfb3a5dfeeb',
    messagingSenderId: '985128793202',
    projectId: 'myfin-194ee',
    storageBucket: 'myfin-194ee.firebasestorage.app',
    iosBundleId: 'com.example.myfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbdYOsYQvzPHek_42xEWdgWqY1HR0Ur_U',
    appId: '1:985128793202:ios:76cfe123e1ccfb3a5dfeeb',
    messagingSenderId: '985128793202',
    projectId: 'myfin-194ee',
    storageBucket: 'myfin-194ee.firebasestorage.app',
    iosBundleId: 'com.example.myfin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmMbDCgXNK49FAgTQaR2qjDVrpaGjUK38',
    appId: '1:985128793202:web:0bede33e7e9431ff5dfeeb',
    messagingSenderId: '985128793202',
    projectId: 'myfin-194ee',
    authDomain: 'myfin-194ee.firebaseapp.com',
    storageBucket: 'myfin-194ee.firebasestorage.app',
  );
}
