// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwg2A6PynNx5Knz8FZ4U9yxVDR6Ryct7E',
    appId: '1:1041698110734:web:863d9abde092327c3c6b5f',
    messagingSenderId: '1041698110734',
    projectId: 'myfin-2f60a',
    authDomain: 'myfin-2f60a.firebaseapp.com',
    storageBucket: 'myfin-2f60a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBBoRsr7_6aM2HfODxuVTXZA-nj_TlPc',
    appId: '1:1041698110734:android:f2e5e07d840137ac3c6b5f',
    messagingSenderId: '1041698110734',
    projectId: 'myfin-2f60a',
    storageBucket: 'myfin-2f60a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9Sol7P9oVbJfFPQPtwP1rCufWSYQ1JQ',
    appId: '1:1041698110734:ios:bfff32edb2f688fb3c6b5f',
    messagingSenderId: '1041698110734',
    projectId: 'myfin-2f60a',
    storageBucket: 'myfin-2f60a.firebasestorage.app',
    iosClientId: '1041698110734-ta1i4kh1hop176vl97k9m82c17v59le7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9Sol7P9oVbJfFPQPtwP1rCufWSYQ1JQ',
    appId: '1:1041698110734:ios:bfff32edb2f688fb3c6b5f',
    messagingSenderId: '1041698110734',
    projectId: 'myfin-2f60a',
    storageBucket: 'myfin-2f60a.firebasestorage.app',
    iosClientId: '1041698110734-ta1i4kh1hop176vl97k9m82c17v59le7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwg2A6PynNx5Knz8FZ4U9yxVDR6Ryct7E',
    appId: '1:1041698110734:web:fb76a0ac5c9e89fc3c6b5f',
    messagingSenderId: '1041698110734',
    projectId: 'myfin-2f60a',
    authDomain: 'myfin-2f60a.firebaseapp.com',
    storageBucket: 'myfin-2f60a.firebasestorage.app',
  );

}